# Generated by Django 4.2 on 2023-05-15 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from snake_app.models import GameDifficulty


def add_data(apps, schema):
    GameDifficulty(level='Легкий').save()
    GameDifficulty(level='Средний').save()
    GameDifficulty(level='Сложный').save()
    GameDifficulty(level='Hardcore').save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField(default=0)),
                ('create_at', models.DateField()),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snake_app.gamedifficulty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(add_data),
    ]
