# Generated by Django 4.2 on 2023-05-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='by_user',
            field=models.TextField(null=True),
        ),
    ]
